#!/usr/bin/python3
# -*- coding: utf-8 -*-
# @Time    : 2022/1/28/10:37
# @Author  : Mr.wen
# @File    : NoahServer.py
# @Software: VScode


import socket
import re
import threading
import os
import sys
import requests
import time
import logging
import json
import tornado.web
import tornado.ioloop
import tornado.options
import tornado.httpserver
import tornado.log

from tornado.escape import json_encode
    
_Ip = socket.gethostbyname(socket.gethostname())

print('ip',_Ip,'...ok')
# port on 80
tornado.options.define('port', default=80, type=int)
if tornado.options.options.port=='80':
    print('port',tornado.options.options.port,'...ok')
    
else:
    logging.warning("port's not 80")


class IndexHandler(tornado.web.RequestHandler):
    def get(self):
        self.render('forum.html', **{'word': ''})
        word = self.get_argument('word')
        print('a man send',word)
        
        
        
def main():
    
    tornado.options.parse_command_line()
    app = tornado.web.Application([(r'/',IndexHandler)],
    template_path=os.path.join(os.path.dirname(__file__),'templates'))
    temPath=os.path.join(os.path.dirname(__file__),'templates')
    logging.info(temPath)
    httpserver = tornado.httpserver.HTTPServer(app)
    logging.info(tornado.options.options.port) 
    httpserver.bind(tornado.options.options.port)
    httpserver.start(1)
    tornado.ioloop.IOLoop.current().start()
    dirname, filename = os.path.split(os.path.abspath(sys.argv[0]))
    logging.info(filename)
    return [filename,tornado.options.options.port]

    
    
if __name__ == '__main__':
    mainret = main()
    print(mainret)

